@startuml
'https://plantuml.com/sequence-diagram
Class Application{
+void start(Stage stage)
+void main():launch
}

Class ToDoListController{
-DatePicker addDate
-TextField addDescription
-Button buttonAdd
-Button buttonAll
-Button buttonCompleted
-Button buttonDelete
-Button buttonEdit
-Button buttonIncomplete
-TableColumn<?, ?> completedCol
-TableColumn<?, ?> dateCol
-TableColumn<?, ?> descriptionCol
-MenuItem open
-MenuItem saveAll
-MenuItem saveList
-TableView<?> tableView
-Tab title
-Button titlebutton
-Button editTitle
-TextField addTitle;

ObservableList<List> data
FilteredList<List> filteredList

initialize(URL location, ResourceBundle resources)

void addButtonClicked()
void editButtonClicked()
void removeButtonClicked()
+void onAll()
+void onCompleted()
+void onIncomplete()
+void onOpen()
+void onSaveAll()
+void onSaveList()
void titleButtonClicked()
void editTitleClicked ()
}

Class List{

SimpleString description;
BooleanProperty completed;
SimpleObjectProperty<LocalDate> deadlineDate;

Task(String description1,  LocalDate date)

+ String getDescription()
+ void setDescription(String deadline1)

+ BooleanProperty getCompleted()
+ void setCompleted(boolean completed1)

+ LocalDate getDeadlineDate()
+ String getDeadline()
+ void setDeadlineDate(LocalDate date)


}


@enduml